### ISSUE TITLE
error: 'EEPROM' was not declared in this scope

### ISSUE THREAD

**Issue by haimbilia** [gromeck/BLE-Scanner#26]
keep getting this error, i tried windows 10 windows 11, latest version of arduino ide and older versions, also tried older versions of the libraries, i tried vscode as well, i get the same error.
![Capture](https://github.com/user-attachments/assets/ebf2d4ab-4337-48cc-b239-2c69f49bf7eb)

**Comment by wprinz** [comment]
Please have  a look at the discussion in the other thread about this topic: https://github.com/gromeck/BLE-Scanner/issues/24
It's a problem caused by the case insensitivity of windows. You need to rename the eeprom und wifi files as an ad hoc workaround.

**Comment by haimbilia** [comment]
> Please have a look at the discussion in the other thread about this topic: #24 It's a problem caused by the case insensitivity of windows. You need to rename the eeprom und wifi files as an ad hoc workaround.

i was just reading it, do you mean the files eeprom.h and wifi.h?

**Comment by wprinz** [comment]
Yes, you need to rename both, the .h and .cpp files to something luke my_wifi.h/.cpp. Afterwards you need to find alle includes of tthe .h files in the other files and need to update these accordingly.

**Comment by wprinz** [comment]
I'v just created a fork into which I have uploaded my files: https://github.com/wprinz/BLE-Scanner/tree/main
You may try that also.

**Comment by haimbilia** [comment]
thank you, i downloaded your fork and it worked

**Comment by wprinz** [comment]
Great! I removed it briefly after creation since I thought that I messed it up. But it's now back in place for the time beeing until this repro is updated: https://github.com/wprinz/BLE-Scanner/tree/main

**Comment by gromeck** [comment]
Could someone check if this is still a problem with v1.0?

**Comment by wprinz** [comment]
Hi, I just downloaded the new version and tried to compile. But the compilation error with eeprom and wifi remains (Win10, Arduino IDE v 2.3.4).

I was able to compile it after I modfied the names to my_wifi.cpp/.h and my_eeprom.cpp/.h and all the includes of these in the other files as with the last version. Maybe you can consider to update this in your code as well?

However, now the ESP 32 doesn't find any bluetooth devices anymore. Not sure, but do I need to perform something on the manufactorer list or is this caused by the major updates in the Nimble libs? I updated all libs to the newest version.

**Comment by wprinz** [comment]
Update: The device is working OK, i.e. it is recognizing other BLE devices - I just didn't recognize/remember that devices that do not send a stable adress are not listed :-)  After adding this hack in bluetooth.cpp it is now listing many devices 
`       if (true || advertisedDevice->getAddressType() == BLE_ADDR_PUBLIC) {
`
Would be nice to make this configurable.

To summarize : The only problem that still remains is that eeprom and wifi should be renamed to support compilation in windows. If you like I can add a branch that you may pull in your version.

**Comment by gromeck** [comment]
> To summarize : The only problem that still remains is that eeprom and wifi should be renamed to support compilation in windows. If you like I can add a branch that you may pull in your version.

If compiling is only an issue unter Arduino IDE v2 on Windows because of a file name clash, this issue should be fixed in the IDE.
I tried a quick search in https://github.com/arduino/arduino-ide/issues without a hit.
I suggest that you create a simple sketch and open a ticket against the IDE v2.

**Comment by gromeck** [comment]
> Update: The device is working OK, i.e. it is recognizing other BLE devices - I just didn't recognize/remember that devices that do not send a stable adress are not listed :-) After adding this hack in bluetooth.cpp it is now listing many devices ` if (true || advertisedDevice->getAddressType() == BLE_ADDR_PUBLIC) {` Would be nice to make this configurable.

Than you should open another issue here -- we will not handle two different issues in one ticket.

**Comment by wprinz** [comment]
> > Update: The device is working OK, i.e. it is recognizing other BLE devices - I just didn't recognize/remember that devices that do not send a stable adress are not listed :-) After adding this hack in bluetooth.cpp it is now listing many devices ` if (true || advertisedDevice->getAddressType() == BLE_ADDR_PUBLIC) {` Would be nice to make this configurable.
> 
> Than you should open another issue here -- we will not handle two different issues in one ticket.

You are right. This enhancement is already discussed here: [https://github.com/gromeck/BLE-Scanner/issues/16](url)

**Comment by wprinz** [comment]
> > To summarize : The only problem that still remains is that eeprom and wifi should be renamed to support compilation in windows. If you like I can add a branch that you may pull in your version.
> 
> If compiling is only an issue unter Arduino IDE v2 on Windows because of a file name clash, this issue should be fixed in the IDE. I tried a quick search in https://github.com/arduino/arduino-ide/issues without a hit. I suggest that you create a simple sketch and open a ticket against the IDE v2.

I believe it's a general issue of the case insensitivity of windows that is causing the problem. I moved the code to Visual Studio Code / PlatformIO and the compilation problem remains. After modifying the file names as described above it compiles ok. 

Anyhow you may close this issue now as other windows user will find enough information about the problem and a possible solution in this discussion.

**Comment by gromeck** [comment]
> > > Update: The device is working OK, i.e. it is recognizing other BLE devices - I just didn't recognize/remember that devices that do not send a stable adress are not listed :-) After adding this hack in bluetooth.cpp it is now listing many devices ` if (true || advertisedDevice->getAddressType() == BLE_ADDR_PUBLIC) {` Would be nice to make this configurable.
> > 
> > 
> > Than you should open another issue here -- we will not handle two different issues in one ticket.
> 
> You are right. This enhancement is already discussed here: [https://github.com/gromeck/BLE-Scanner/issues/16](url)

Ooops, I wasn't aware of that ;-) 
So, than it's on the list ... give me some time to implement it.

**Comment by MutantHeadcase** [comment]
> I was able to compile it after I modfied the names to my_wifi.cpp/.h and my_eeprom.cpp/.h and all the includes of these in the other files as with the last version. Maybe you can consider to update this in your code as well?

@wprinz, I followed your lead and landed on new errors on Windows. Looks like function names are colliding. For example...

C:/Users/kyles/AppData/Local/Arduino15/packages/esp32/tools/esp-rv32/2511/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld.exe: C:\Users\kyles\AppData\Local\arduino\sketches\A57B2557B3243CC43EDEAFE57E36E617\sketch\objs.a(eeprom.cpp.o): in function `EepromInit(int)':
C:\Projects\Device-Counter-Arduino\BLE-Scanner/eeprom.cpp:35: multiple definition of `EepromInit(int)'; C:\Users\kyles\AppData\Local\arduino\sketches\A57B2557B3243CC43EDEAFE57E36E617\sketch\objs.a(ble-eeprom.cpp.o):C:\Projects\Device-Counter-Arduino\BLE-Scanner/ble-eeprom.cpp:35: first defined here 

Am I missing something?

**Comment by MutantHeadcase** [comment]
I prefixed all the functions in the my- versions of the files to make their names unique. Past those errors. On to the next.
